# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{remarkable_rails}
  s.version = "4.0.0.alpha4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Carlos Brando", "Jos\303\251 Valim"]
  s.date = %q{2011-09-09}
  s.description = %q{Remarkable Rails: collection of matchers and macros with I18n for Rails}
  s.email = ["eduardobrando@gmail.com", "jose.valim@gmail.com"]
  s.extra_rdoc_files = [
    "CHANGELOG",
     "LICENSE",
     "README"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README",
     "lib/remarkable_rails.rb",
     "lib/remarkable_rails/action_controller.rb",
     "lib/remarkable_rails/action_controller/base.rb",
     "lib/remarkable_rails/action_controller/macro_stubs.rb",
     "lib/remarkable_rails/action_controller/matchers/assign_to_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/filter_params_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/redirect_to_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/render_template_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/respond_with_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/route_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/set_cookies_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/set_session_matcher.rb",
     "lib/remarkable_rails/action_controller/matchers/set_the_flash_matcher.rb",
     "lib/remarkable_rails/action_view.rb",
     "lib/remarkable_rails/action_view/base.rb",
     "lib/remarkable_rails/active_orm.rb",
     "locale/en.yml"
  ]
  s.homepage = %q{http://github.com/carlosbrando/remarkable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{remarkable}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Remarkable Rails: collection of matchers and macros with I18n for Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.0.alpha11"])
      s.add_runtime_dependency(%q<rspec-rails>, [">= 2.0.0.alpha11"])
      s.add_runtime_dependency(%q<remarkable>, ["~> 4.0.0.alpha4"])
      s.add_runtime_dependency(%q<remarkable_activerecord>, ["~> 4.0.0.alpha4"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.alpha11"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0.alpha11"])
      s.add_dependency(%q<remarkable>, ["~> 4.0.0.alpha4"])
      s.add_dependency(%q<remarkable_activerecord>, ["~> 4.0.0.alpha4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.alpha11"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0.alpha11"])
    s.add_dependency(%q<remarkable>, ["~> 4.0.0.alpha4"])
    s.add_dependency(%q<remarkable_activerecord>, ["~> 4.0.0.alpha4"])
  end
end

